name: Build and Compile Oyster Linter VS Code Extension

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc -p ./

      - name: Lint code
        run: npx tsc --noEmit

      - name: Build with webpack
        run: npx webpack --config webpack.config.js

      - name: Package VS Code Extension
        if: github.event_name == 'workflow_dispatch'
        run: npx vsce package

      - name: Get version from package.json
        if: github.event_name == 'workflow_dispatch'
        id: version
        run: |
          echo "version=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version  }}
          name: Oyster Linter v${{ steps.version.outputs.version  }}
          files: ${{ github.workspace }}/*.vsix
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: "true"
      
      - name: Publish VSIX
        if: github.event_name == 'workflow_dispatch'
        run: npx vsce publish ${{ secrets.PUBLISHER_ID }} || ${{ secrets.MARKETPLACE_PAT}}
