name: Build and Compile Oyster Linter VS Code Extension

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc -p ./

      - name: Lint code
        run: npx tsc --noEmit

      - name: Install webpack
        run: npm install -D webpack-cli
      
      - name: Install Clean Webpack Plugin
        run: npm install -D clean-webpack-plugin

      - name: Install path
        run: npm install -D path

      - name: Install TS Loader
        run: npm install -D ts-loader

      - name: Build with webpack
        run: npx webpack --config webpack.config.js

      - name: Package VS Code Extension
        if: github.event_name != 'pull_request'
        run: npx vsce package

      - name: Upload VSIX artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: oyster-linter-vsix
          path: "*.vsix"

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions: 
      contents: write
    steps:
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: oyster-linter-vsix
          path: ./

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${{ github.run_number }}.${{github.run_attempt}}-prerelease
          release_name: "Oyster Linter v0.${{ github.run_number }}.${{github.run_attempt}}-prerelease (Prerelease)"
          prerelease: true
          draft: false

      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/oyster-linter-vsix
          asset_name: oyster-linter-vsix.zip
          asset_content_type: application/zip
